# Generated by Django 3.1 on 2020-09-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='name',
        ),
        migrations.AddField(
            model_name='loan',
            name='DecisionMadeBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
