# Generated by Django 3.1 on 2020-09-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0002_auto_20200920_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IsLoanOfficer',
            field=models.BooleanField(default=False, verbose_name='Loan Officer'),
        ),
    ]
